version: '3.1'
services:
  backend:
    build:
      context: ../packages/backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - ENV=LOCAL

  frontend:
    build:
      context: ../packages/ui/
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - REACT_APP_WS_HOST=localhost
      - REACT_APP_WS_PORT=5000
