core:
  openai_api_key:
    tag: "core"
    description: "API key for accessing OpenAI services."
  
  stabilityai_api_key:
    tag: "core"
    description: "API key for accessing Stability AI services."
  
  replicate_api_key:
    tag: "core"
    description: "API key for accessing Replicate services."
