name: Docker Compose Build and Healthcheck

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download wait-for-it
      run: |
        wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
        chmod +x wait-for-it.sh

    - name: Move to docker directory and run docker-compose
      run: |
        cd docker
        docker-compose up -d

    - name: Wait for service to be ready
      run: ./wait-for-it.sh localhost:5000 --timeout=120 --strict

    - name: Healthcheck server
      run: curl -v --fail http://localhost:5000/healthcheck
